micronaut:
  application:
    name: pedagioApi
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pedagio_tambore
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Nath@1308
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
